#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

script=$(basename "$0")

function usage {
	echo "Set active AWS credentials from user, role or env."
	echo
	echo "Works seemlessly with the CLI and SDKs, since the desired credentials"
	echo "are copied into the 'default' in ~/.aws/credentials."
	echo
	echo "Uses the CLI for any heavy lifting, so features like MFA etc."
	echo "should just work."
	echo
	echo "IMPORTANT: Move your 'default' credentials before using, since this"
	echo "script will maintain that section. Keep your users and roles in"
	echo "named sections."
	echo
	echo "Usage:"
	echo "$ ${script} role <profile in ~/.aws/config>"
	echo "$ ${script} user <profile in ~/.aws/credentials>"
	echo "$ ${script} env (sets active credentials from env vars)"
	echo "$ ${script} whoami (shows active credentials)"
	echo "$ ${script} no (unsets active credentials)"
	echo "$ ${script} sts_region <region> (set STS region to use)"
	exit 1
}

AWS_DIR=~/.aws
AWS_CACHE_DIR=${AWS_DIR}/cli/cache

# Ensure files exist and have final newlines (`aws configure` messes up otherwise).
mkdir -p "${AWS_DIR}"
touch "${AWS_DIR}/config"
touch "${AWS_DIR}/credentials"
[[ -n $(tail -c1 "${AWS_DIR}/config") ]] && echo >> "${AWS_DIR}/config"
[[ -n $(tail -c1 "${AWS_DIR}/credentials") ]] && echo >> "${AWS_DIR}/credentials"

# Check dependencies.
which aws > /dev/null || (echo "Missing dependency: aws" && false)
which jq > /dev/null || (echo "Missing dependency: jq" && false)

function write_signature {
	# Saves to ~/.aws/config:
	aws configure set default.managed_by "${script}"
}

function set_default_credentials {
	access_key_id=$1
	secret_access_key=$2
	session_token=$3

	# Saves to ~/.aws/credentials:
	aws configure set default.aws_access_key_id "${access_key_id}"
	aws configure set default.aws_secret_access_key "${secret_access_key}"
	aws configure set default.aws_session_token "${session_token}"
}

action=${1:-}

if [[ "${action}" == "" ]]; then
	usage
fi

if [[ "${action}" == "env" ]]; then
	# Grab the desired credentials.
	access_key_id="${AWS_ACCESS_KEY_ID:-}"
	if [[ "${access_key_id}" == "" ]]; then
		echo "!!! AWS_ACCESS_KEY_ID must be set in env"
		exit 1
	fi
	secret_access_key="${AWS_SECRET_ACCESS_KEY:-}"
	if [[ "${secret_access_key}" == "" ]]; then
		echo "!!! AWS_SECRET_ACCESS_KEY must be set in env"
		exit 1
	fi
	session_token="${AWS_SESSION_TOKEN:-}"

	set_default_credentials "${access_key_id}" "${secret_access_key}" "${session_token}"

	write_signature

	echo "Set default credentials from env vars (with ID: ${access_key_id})"
	echo
	echo "NOTE: You no longer need the AWS_* variables in your shell, so feel"
	echo "to unset them or exit this shell."
	exit 0
fi

if [[ "${AWS_ACCESS_KEY_ID:-}" != "" ]]; then
	echo "WARNING: AWS_ACCESS_KEY_ID exists in env and may cause unwanted behavior"
fi
if [[ "${AWS_SECRET_ACCESS_KEY:-}" != "" ]]; then
	echo "WARNING: AWS_SECRET_ACCESS_KEY exists in env and may cause unwanted behavior"
fi
if [[ "${AWS_SESSION_TOKEN:-}" != "" ]]; then
	echo "WARNING: AWS_SESSION_TOKEN exists in env and may cause unwanted behavior"
fi
if [[ "${AWS_PROFILE:-}" != "" ]]; then
	echo "WARNING: AWS_PROFILE exists in env and may cause unwanted behavior"
fi

if [[ "${action}" == "no" ]]; then
	set_default_credentials "" "" ""

	write_signature

	echo "Cleared default credentials"
	exit 0
fi

if [[ "${action}" == "sts_region" ]]; then
	sts_region=${2:-}
	if [[ "${sts_region}" == "" ]]; then
		echo "!!! Second arg must be an AWS region, like eu-west-1"
		exit 1
	fi
	aws configure set sts_region "${sts_region}" --profile "${script}"

	echo "Set STS region to: ${sts_region}"
	exit 0
fi

# Fetch region to use for STS endpoint.
sts_region=$(aws configure get ${script}.sts_region || echo)
if [[ "${sts_region}" == "" ]]; then
	echo "--- NOTE: To optimize me, tell me a region close to you:"
	echo "--- For example: ${script} sts_region eu-west-1"
	echo
else
	export AWS_REGION="${sts_region}"
fi

if [[ "${action}" == "whoami" ]]; then
	aws sts get-caller-identity

	exit 0
fi

profile=${2:-}

if [[ "${profile}" == "" ]]; then
	echo "!!! Second arg must be an AWS profile (in ~/.aws)!"
	echo
	usage
fi

if [[ "${action}" == "user" ]]; then
	# Grab the desired credentials.
	access_key_id=$(aws configure get ${profile}.aws_access_key_id || echo)
	if [[ "${access_key_id}" == "" ]]; then
		echo "!!! Could not find access_key_id for user: ${profile}"
		exit 1
	fi
	secret_access_key=$(aws configure get ${profile}.aws_secret_access_key)
	if [[ "${secret_access_key}" == "" ]]; then
		echo "!!! Could not find secret_access_key for user: ${profile}"
		exit 1
	fi
	session_token=$(aws configure get ${profile}.aws_session_token || echo)

	set_default_credentials "${access_key_id}" "${secret_access_key}" "${session_token}"

	write_signature

	echo "Set default credentials from user: ${profile}"
	exit 0
fi

if [[ "${action}" == "role" ]]; then
	# Let the AWS CLI assume a role for us (using exported profile), prompt
	# for MFA if necessary, and save credentials to cache.
	export AWS_PROFILE=${profile}
	user_id=$(aws sts get-caller-identity | jq --raw-output '.UserId')

	# Fetch credentials from cache.
	creds=
	for file in $(ls $AWS_CACHE_DIR/*.json); do
		contents=$(cat $file)
		role_id=$(echo $contents | jq --raw-output '.AssumedRoleUser.AssumedRoleId')
		if [[ $user_id == $role_id ]]; then
			creds=$(echo $contents | jq --raw-output '.Credentials')
			break
		fi
	done

	if [[ "${creds}" == "" ]]; then
		echo "!!! Could not assume role!"
		exit 2
	fi

	access_key_id=$(echo $creds | jq --raw-output '.AccessKeyId')
	secret_access_key=$(echo $creds | jq --raw-output '.SecretAccessKey')
	session_token=$(echo $creds | jq --raw-output '.SessionToken')

	set_default_credentials "${access_key_id}" "${secret_access_key}" "${session_token}"

	write_signature

	echo "Set default credentials from role: ${profile}"
	exit 0
fi

echo "!!! Unknown arguments"
echo
usage
